name: IPTV Checker Workflow

on:
  schedule:
    # 每天 00:00 UTC (北京时间 08:00) 运行
    - cron: '0 */6 * * *'  
  workflow_dispatch: # 支持手动点击运行
env:
  TZ: Asia/Shanghai
jobs:
  check-iptv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24' # 建议使用最新的 LTS 版本

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install iptv-checker
        run: npm install -g iptv-checker

      - name: Run IPTV Checker
        run: |
          # 确保输入文件 best_sorted.m3u 存在于你的仓库根目录
          iptv-checker -o iptv-output -p 10 -k best_sorted.m3u

      - name: Commit and Push results
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add iptv-output/
          git commit -m "Update checked IPTV list" || echo "No changes to commit"
          git push